@baseUrl = http://localhost:4002

###create user
POST {{baseUrl}}/user-api/users
Content-Type: application/json

{
    "name":"mickey",
    "email":"mickey@gmail.com",
    "dob":"2002-08-12",
    "mobileno":"9878976533"
}


### read all users
GET {{baseUrl}}/user-api/users


###read user by id
GET {{baseUrl}}/user-api/users/69ccfe499d0fc22d92a1f0f6

###Soft Delete by id
DELETE  {{baseUrl}}/user-api/users/69ccfe499d0fc22d92a1f0f6

###activate user
PATCH {{baseUrl}}/user-api/users/69ccfe499d0fc22d92a1f0f6